---

port: 4000
host: 0.0.0.0
safe: false


### site serving configuration ###
exclude: [CNAME, README.md, .gitignore]
permalink: /:title ## disables post output
timezone: null
lsi: false
markdown: kramdown
highlighter: rouge


### content configuration ###
title:       "SoCraTes IT 2018"
keywords:    "openspace, unconference, SoCraTes, software, craftsmanship, testing, italy, international"
description: "3rd International Software Craftsmanship and Testing Conference in Italy"
source_link: "https://socrates-it.github.io"
favicon:     "img/favicon.ico"
touch_icon:  "img/apple-touch-icon.png"
google_analytics_key: UA-70508315-1 ## put YOUR key here to enable tracking! (blank to disable)


### template colors, used site-wide via css ###
colors:
  black:          '#111111'
  white:          '#F1F2F1'
  blue:           '#49a7e9'
  green:          '#009246'
  purple:         '#c869bf'
  orange:         '#fab125'
  turquoise:      '#0fbfcf'
  red:            '#CE2B37'
  gray:           '#DDDDDD'
  socratesblue:   '#3F51B5'

kramdown:
  auto_ids:  false
  input: GFM
